// Generated by CoffeeScript 1.3.3
(function() {
  var Client, net;

  net = require('net');

  Client = (function() {

    function Client(config) {
      this.port = config.port || 9090;
      this.host = config.host || '127.0.0.1';
    }

    Client.prototype.call = function(request, callback) {
      var client;
      client = new net.Socket();
      client.connect(this.port, this.host, function() {
        return client.write(JSON.stringify(request));
      });
      return client.on('data', function(data) {
        return callback(JSON.parse(data));
      });
    };

    return Client;

  })();

  module.exports = Client;

}).call(this);
