// Generated by CoffeeScript 1.3.3
(function() {
  var Server, net;

  net = require('net');

  Server = (function() {

    function Server(config) {
      this.exposes = config.exposes;
      this.port = config.port || 9090;
      this.host = config.host || '127.0.0.1';
    }

    Server.prototype.run = function(callback) {
      var server;
      server = net.createServer();
      server.on('connection', function(connection) {
        return connection.on('data', function(request) {
          return callback(connection, JSON.parse(request));
        });
      });
      return server.listen(this.port, this.host);
    };

    Server.prototype.call = function(request, callback) {
      var args, className, key, response, value;
      className = request['class'].replace('::', '.');
      args = (function() {
        var _ref, _results;
        _ref = request["arguments"];
        _results = [];
        for (key in _ref) {
          value = _ref[key];
          _results.push(value);
        }
        return _results;
      })();
      response = this.exposes[className][request.method].apply(null, args);
      return callback(response);
    };

    Server.prototype.push = function(connection, response) {
      connection.write(JSON.stringify(response));
      return connection.end();
    };

    return Server;

  })();

  module.exports = Server;

}).call(this);
